# CodeRabbit Configuration for VisionCheck AI
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

version: 2

language: en-US

early_access: false

reviews:
  # Enable automated code reviews
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false
  review_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  
  # Auto-review settings
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master

  # Path-based review configuration
  path_filters:
    # Exclude binary and media files
    - "!**/*.mp3"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.ico"
    - "!**/*.webp"
    - "!**/*.woff"
    - "!**/*.woff2"
    - "!**/*.ttf"
    - "!**/*.eot"
    # Exclude lock files
    - "!**/package-lock.json"
    - "!**/yarn.lock"
    - "!**/pnpm-lock.yaml"
    # Exclude generated files
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/coverage/**"
    - "!**/playwright-report/**"
    - "!**/test-results/**"

  # Path-specific review instructions
  path_instructions:
    - path: "src/components/**/*.jsx"
      instructions: |
        Review React components for:
        - Proper use of React hooks (useState, useEffect, useContext, etc.)
        - Accessibility best practices (ARIA attributes, keyboard navigation, semantic HTML)
        - Component reusability and proper prop types
        - Memory leaks in useEffect cleanup
        - Performance optimizations (useMemo, useCallback where appropriate)
    
    - path: "src/context/**/*.jsx"
      instructions: |
        Review React Context implementations for:
        - Proper context value memoization to prevent unnecessary re-renders
        - Clear separation of concerns
        - Appropriate default values
        - Context provider placement recommendations
    
    - path: "src/pages/**/*.jsx"
      instructions: |
        Review page components for:
        - Proper routing integration with react-router-dom
        - Page-level error handling
        - Loading states for async operations
        - SEO and accessibility considerations
        - Mobile responsiveness with Tailwind CSS
    
    - path: "**/*.test.jsx"
      instructions: |
        Review unit tests for:
        - Adequate test coverage of component behavior
        - Proper use of React Testing Library queries (prefer getByRole, getByLabelText over getByTestId)
        - Testing user interactions rather than implementation details
        - Proper async handling with waitFor/findBy queries
        - Clear test descriptions following "should..." pattern
    
    - path: "e2e/**/*.spec.js"
      instructions: |
        Review Playwright E2E tests for:
        - Reliable selectors (prefer accessible selectors)
        - Proper waiting strategies to avoid flaky tests
        - Test isolation and cleanup
        - Mobile viewport testing coverage
        - Meaningful assertions that verify user-visible behavior
    
    - path: "src/api/**/*.js"
      instructions: |
        Review API integrations for:
        - Proper error handling and user feedback
        - Input validation before API calls
        - Secure handling of API keys (should never be logged or exposed)
        - Rate limiting considerations
        - Graceful degradation when API is unavailable
    
    - path: "src/i18n/**/*.json"
      instructions: |
        Review translation files for:
        - Consistent key naming conventions
        - Complete translations across all supported languages
        - Proper pluralization handling
        - No hardcoded text that should be translated

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  linear:
    team_keys: []
  pull_requests:
    scope: auto
